name: ghethanhpham_thaco
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  shared_preferences: ^2.2.1
  easy_localization: ^3.0.3
  package_info_plus: ^4.1.0
  flutter_downloader: ^1.10.2
  provider: ^6.0.5
  rounded_loading_button: ^2.1.0
  font_awesome_flutter: ^10.5.0
  http: ^1.1.0
  intl: ^0.18.1
  path_provider: ^2.0.15
  loading_animation_widget: ^1.2.0+4
  easy_autocomplete: ^1.6.0
  install_plugin: ^2.1.0
  flutter_barcode_scanner: ^2.0.0
  mobile_scanner: ^2.1.0
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/animations/
  fonts:
    - family: MyriadPro
      fonts:
        - asset: assets/fonts/Myriad-Pro-Light.ttf
          weight: 300
        - asset: assets/fonts/Myriad-Pro-Regular.ttf
          weight: 400
        - asset: assets/fonts/Myriad-Pro-Bold.ttf
          weight: 700


